services:
  icecast:
    image: infiniteproject/icecast
    ports:
      - "8000:8000"
    environment:
      ICECAST_SOURCE_PASSWORD: hackme
      ICECAST_ADMIN_PASSWORD: hackme
      ICECAST_HOSTNAME: localhost
      ICECAST_MAX_SOURCES: 8

  liquidsoap-zoo:
    image: savonet/liquidsoap:v2.3.1
    depends_on:
      - icecast
    volumes:
      - ./episodes:/episodes
      - ./config/liquidsoap:/config
      - ./archive:/archive
      - ./.tmp:/tmp-tracks
    command: liquidsoap /config/zoo.liq
    ports:
      - "1234:1234"

  liquidsoap-crate:
    image: savonet/liquidsoap:v2.3.1
    depends_on:
      - icecast
    volumes:
      - ./tracks:/tracks
      - ./config/liquidsoap:/config
      - ./archive:/archive
      - ./.tmp:/tmp-tracks
    command: liquidsoap /config/crate.liq
    ports:
      - "1235:1235"

  liquidsoap-conspiracy:
    image: savonet/liquidsoap:v2.3.1
    depends_on:
      - icecast
    volumes:
      - ./episodes:/episodes
      - ./config/liquidsoap:/config
      - ./archive:/archive
      - ./.tmp:/tmp-tracks
    command: liquidsoap /config/conspiracy.liq
    ports:
      - "1236:1236"

  liquidsoap-request:
    image: savonet/liquidsoap:v2.3.1
    depends_on:
      - icecast
    volumes:
      - ./tracks:/tracks
      - ./config/liquidsoap:/config
      - ./archive:/archive
      - ./.tmp:/tmp-tracks
    command: liquidsoap /config/request.liq
    ports:
      - "1237:1237"
